name: tesla_android
description: Tesla Android

publish_to: 'none'

version: 2024.24.1

environment:
  flutter: "3.22.0"
  sdk: "3.4.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  retrofit: ^4.1.0
  pointer_interceptor: ^0.9.0+1
  get_it: ^7.0.0
  injectable: ^2.1.0
  flavor: ^2.0.0
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  flutter_markdown: ^0.6.10
  qr_flutter: ^4.0.0
  logger: any
  json_serializable: ^6.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.1.1
  equatable: ^2.0.0
  web_socket_client: ^0.1.0-dev.3
  web: ^0.5.1

  json_annotation: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: '>=2.3.0 <4.0.0'
  injectable_generator: ^2.1.3
  retrofit_generator: ^8.1.0

flutter:
  assets:
    - images/png/
    - fonts/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
