name: tesla_android
description: Tesla Android

publish_to: 'none'

version: 2025.51.1

environment:
  flutter: "3.35.0"
  sdk: "3.9.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 5.9.0
  retrofit: 4.7.2
  pointer_interceptor: 0.10.1+2
  get_it: 8.2.0
  injectable: 2.5.1
  flavor: ^2.0.0
  flutter_bloc: 9.1.1
  rxdart: 0.28.0
  shared_preferences: 2.5.3
  flutter_markdown: 0.7.7+1
  qr_flutter: 4.1.0
  logger: 2.6.1
  json_serializable: 6.11.1
  package_info_plus: 8.3.1
  url_launcher: 6.3.2
  equatable: 2.0.7
  web_socket_client: 0.2.1
  web: 1.1.1
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.7.1
  injectable_generator: 2.8.1
  retrofit_generator: 10.0.5

flutter:
  assets:
    - images/png/
    - fonts/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
