name: tesla_android
description: Tesla Android

publish_to: 'none'

version: 2024.9.1

environment:
  flutter: "3.13.3"
  sdk: "3.1.1"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  retrofit: '>=4.0.0 <5.0.0'
  pointer_interceptor: ^0.9.0+1
  get_it: ^7.0.0
  injectable: ^2.1.0
  flavor: ^2.0.0
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  flutter_markdown: ^0.6.10
  qr_flutter: ^4.0.0
  logger: any
  json_serializable: ^6.2.0
  package_info_plus: ^4.1.0
  sentry_flutter: ^7.5.2
  sentry_dio: ^7.5.2
  url_launcher: ^6.1.1
  equatable: ^2.0.0
  aptabase_flutter: ^0.1.0
  web_socket_client: ^0.1.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: '>=2.3.0 <4.0.0'
  injectable_generator: ^2.1.3
  retrofit_generator: ^7.0.8

flutter:
  assets:
    - images/png/
    - fonts/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
