name: tesla_android
description: Tesla Android

publish_to: 'none'

version: 2023.16.5+1

environment:
  flutter: "3.7.0"
  sdk: "2.19.0"

dependencies:
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.9.0+1
  http: ^0.13.4
  web_socket_channel: ^2.2.0
  get_it: ^7.0.0
  injectable: ^2.1.0
  flavor: ^2.0.0
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  flutter_markdown: ^0.6.10
  qr_flutter: ^4.0.0
  logger: any
  json_serializable: ^6.2.0
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter:
  assets:
    - images/png/
    - fonts/
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
